name: soiling_model_env
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - openpyxl=3.0.9
  - numpy=1.21.2
  - ipykernel=6.4.1
  - matplotlib=3.5.0
  - scipy=1.7.3
  - pandas=1.3.5
  - numdifftools=0.9.39
  - pip=21.2.4
  - windrose=1.8.1
  - pip:
    - miepython
